#sec
#DISKSEC1=sde1

##legacy
DISKR1=$DISKRAID1
DISKR2=$DISKRAID2
DISKR3=$DISKRAID3
DISKR4=$DISKRAID4
DISKR5=$DISKRAID5
DISKR6=$DISKRAID6
DISKR7=$DISKRAID7
DISKR8=$DISKRAID8


#Работа
DISKRES1=$DISKRES1
DISKRES2=$DISKRES1
DISKRES3=$DISKRES1
DISKRES4=$DISKRES1
DISKRES5=$DISKRES1
DISKRES6=$DISKRES1

LABELRES1=$LABELRES1
LABELRES2=$LABELRES1
LABELRES3=$LABELRES1
LABELRES4=$LABELRES1
LABELRES5=$LABELRES1
LABELRES6=$LABELRES1

LABELTMP1=$LABELSD1
LABELTMP2=$LABELSD1
LABELTMP3=$LABELSD1
LABELTMP4=$LABELSD1
LABELTMP5=$LABELSD1
LABELTMP6=$LABELSD1

LABELSEC1=$LABELSEC1
LABELSEC2=$LABELSEC1
LABELSEC3=$LABELSEC1
LABELSEC4=$LABELSEC1
LABELSEC5=$LABELSEC1
LABELSEC6=$LABELSEC1

