DISKBCACHE1=$DISKRAID1
DISKBCACHE2=$DISKRAID2
DISKBCACHE3=$DISKRAID3
DISKBCACHE4=$DISKRAID4
DISKBCACHE5=$DISKRAID5


DISKRAID1=bcache0
DISKRAID2=bcache1
DISKRAID3=bcache2
DISKRAID4=bcache3
DISKRAID5=bcache4
